name: call workflow
on:
  # Manual trigger from the UI
 # workflow_dispatch:
 #   inputs:
 #     message:
 #       description: 'call from ui'

  # Dependency to forking workflow
  workflow_run:
    workflows: ["dispatch workflow"]
    type:
      - complete
jobs:
  call_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: msg
        run: echo "Invoked by dispatch workflow"
